# Generated by Django 5.1.1 on 2024-10-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(null=True)),
                ('pertanyaan', models.CharField(max_length=225)),
                ('jawaban', models.CharField(max_length=225)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
